#ifndef COMLIBSERVICES_H
#define COMLIBSERVICES_H

#define COMMUNICATION_LIBRARY 0
#define DB_SERV 1
#define DB_SERV_WRITE_CONFIG_REQ 2
#define BLSTARTUP_INTIALIZATION 3
#define CAN_SERV 4
#define DB_SERV_WRITE_CAN_DATA_REQ 5
#define APPMAN_SERVICE 6
#define STARTUP_SERV 7
#define APPMAN_SERVICE_ASK_UI_FOR_REBOOT_REQ 8
#define BLSTARTUP_DOCUMENT_AVAILABLE 9
#define BLSTARTUP_SERVICEREADY 10
#define PACKAGE_MANAGER_SERV 11
#define BLSTARTUP_UNASSIGNED 12
#define APPMAN_SERVICE_FORCE_REBOOT_REQ 13
#define REGISTRATION_DATA 14
#define HEARTBEAT_DATA 15
#define HEARTBEAT_DYNAMICDATA 16
#define SYSTEMHEALTH_DATA 17
#define SYSTEMHEALTH_DYNAMICDATA 18
#define UPLOAD_SERV 19
#define REGISTRATION_DYNAMICDATA 20
#define REGISTRATION_DATARESPONSE 21
#define DOWNLOAD_SERV 22
#define DOWNLOAD_CONFIG_DATA 23
#define WRITE_CONFIG_DATA 24
#define RFID_SERV 25
#define CAN_SERV_NAME "CAN_SERV"
#define DB_SERV_NAME "DB_SERV"
#define APPMAN_SERVICE_NAME "APPMAN_SERV"
#define REGISTER_SERV_DELAY 3000
#define CAN_SERV_DELEGATE 30
#define BATTEY_BIN_ID_MessageMacro 31
#define BSS_Batt_Chg_BIN_Lock_State_MessageMacro 32
#define BSS_BattChgRemainTimeMessageMacro 33
#define BSS_BattSocEstPercMessageMacro 34
#define BSS_BattStateMessageMacro 35
#define BSS_BattEnergyMeterAverageCurrentMessageMacro 36
#define BSS_BattEnergyMeterCurrentMessageMacro 37
#define BSS_EnergyMeterTotalKiloWattMessageMacro 38
#define BSS_EnergyMeterVoltageMessageMacro 39
#define BSS_HVAC_Electrical_Param_MessageMacro 40
#define BSS_HVAC_FAN_Param_MessageMacro 41
#define BSS_HVAC_SW_Ver_Unit_MessageMacro 42
#define BSS_HVAC_Temp_Param_MessageMacro 43
#define BSS_Sen_Resp_MessageMacro 44
#define BSS_SensorInterface_Stat_MessageMacro 45
#define BSS_TempHumiditySensor_MessageMacro 46
#define BSS_EnergyMeterKiloVoltAmpereMessageMacro 47
#define BSS_EnergyMeterKiloWattMessageMacro 48
#define BSS_EnergyMeterParamMessageMacro 49
#define BSS_ChgConfig_MessageMacro 50
#define BSS_Control_Param_MessageMacro 51
#define BSS_HVAC_Control_Param_MessageMacro 52
#define BSS_OTA_Req_MessageMacro 53
#define BSS_Sen_ControlComm_MessageMacro 54
#define COMM_CHG_Param_MessageMacro 55
#define BT_SERV 56
#define DC_COMM_Version_SW_HW_MessageMacro 57
#define CHG_Version_SW_HW_And_Max_Output_MessageMacro 58
#define CHG_Manufacture_Code_MessageMacro 59
#define Heart_Beat_Fixed_Part_CAN_MessageMacro 63
#define Heart_Beat_Dynamic_Part_CAN_MessageMacro 64
#define System_Health_Fixed_Part_CAN_MessageMacro 65
#define System_Health_Dynamic_Part_CAN_MessageMacro 66
#define GET_DEVICE_INFO 67
#define GET_SYSTEM_INFO 68
#define GET_SYSTEM_SYNC 69
#define GET_PORT_DETAILS 70
#define GET_CONFIG 71
#define SET_CONFIG_WIFI_CREDENTIALS 72
#define SET_CONFIG_SERVER_DETAILS 73
#define CTRL_CMD_CHARGER_ON 74
#define CTRL_CMD_CHARGER_OFF 75
#define CTRL_CMD_LOCK_OPEN 76
#define SET_ACCESS_TYPE 77
#define BLE_Device_Info_Fixed_Part_CAN_MessageMacro 78
#define BLE_Device_Info_Dynamic_Part_CAN_MessageMacro 79
#define BLE_System_Info_Fixed_Part_CAN_MessageMacro 80
#define BLE_System_Sync_MessageMacro 81
#define BLE_Port_MessageMacro 82
#define CTRL_CMD_CHARGER_Response 83
#define CTRL_CMD_LOCK_OPEN_Response 84
#define DB_SERV_HBDATA_LOG_REQ 85
#define DB_SERV_SHDATA_LOG_REQ 86
#define WIFI_SERV 87
#define CAN_SERV_UPDATE 88
#define GSM_SERV 89
#define FOTA_SERV 90
#define OTARequestMessageMacro 91
#define BSS_OTA_Resp_MessageMacro 92
#define BattFlash_Boot_Start_MessageMacro 93
#define BattFlash_Boot_Start_Ack_MessageMacro 94
#define BattFlash_Boot_Firmware_Data_MessageMacro 95
#define BattFlash_Boot_Success_Check_MessageMacro 96
#define CONNECTIONMANAGER_SERV 97
#define WIFI_SERV_UPDATE 98
#define GSM_SIGNAL_UPDATE 99
#define WifiSignalStrengthMessageMacro 100
#define ConnectWifiMessageMacro 101
#define DisconnectWifiMessageMacro 102
#define BLE_CONNECTION_STATUS_UPDATE 103

#endif // COMLIBSERVICES_H
